### ISSUE TITLE
shortCut 

### ISSUE THREAD

**Issue by robinhood3351** [Novin24/NeAccounting_wpf#190]
افزودن کلید میانبر به تمامی صفحات

- [x] تمام دکمه ثبت ها (F1) شود
- [x] تمام دکمه ثبت فیلد های فاکتور (F2) شود
- [x] داخل فاکتور ثبت مشتری و اجناس لحاظ شود
- [x] کلید میانبر برای صورتحساب 
- [x] کلید میانبر برای ریزصورتحساب

**Comment by 7607711** [comment]
در صورتی F2 کار میکنه که TEXTBOX انتخاب شده باشد
